# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

HEADERS += AGProject1.h \
			AG1graphic.h 
SOURCES += main.cpp \
			AGProject1.cpp \
			AG1graphic.cpp 
FORMS   += AGProject1.ui
TARGET = AGProject1
QT += widgets
CONFIG += debug
			